name: CI Pipeline

on:
<<<<<<< HEAD
  push:
    branches:
      - development  # Trigger on pushes to the development branch
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes in UTC
  workflow_dispatch:  # Allow manual trigger
=======
    push:
      branches: [development]  # Trigger on pushes to main
    schedule:
      - cron: '*/5 * * * *'  # Every Sunday at 00:00 UTC
    workflow_dispatch:  # Allow manual trigger
  
>>>>>>> 8d8849ec4b75aee3b9275d6b37ae5ad7ceacde95

permissions:
  contents: write

jobs:
  delete-stale-branches:
    name: Delete Stale Branches
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Delete branches inactive for more than 60 days
        uses: crs-k/stale-branches@v6.0.2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 59
          days-before-delete: 60
          dry-run: false
          branches-filter-regex: '^(?!main$|production$|development$).*'
          comment-updates: false
<<<<<<< HEAD
=======
          max-issues: 0
>>>>>>> 8d8849ec4b75aee3b9275d6b37ae5ad7ceacde95
